# Generated by Django 4.1.5 on 2023-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('name', 'chat_id'), name='unique_chat_constraint'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='chat',
            field=models.ManyToManyField(to='vacancies.chat'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time',
            field=models.ManyToManyField(to='vacancies.vacancytime'),
        ),
    ]
