# Generated by Django 4.1.5 on 2023-02-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_chat_vacancytime_chat_unique_chat_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='client',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='vacancies.telegramclient'),
        ),
    ]
