# Generated by Django 4.1.5 on 2023-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_client_vacancy_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='chat',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='vacancies.chat'),
        ),
    ]
